function preparedfluxRegressionTable = prepareFluxModerationRegressionResults(filePath)
fluxRegressionTable = readtable(filePath,'VariableNamingRule','preserve');

% Change variable names
oldNames = fluxRegressionTable.Properties.VariableNames;

% Define new names
newNames = {...
    'Maximised WBM reaction',...
    'Regression formula',...
    'Predictor of interest',...
    'Distribution of dependent variable',...
    'Analysed samples',...
    ...'PD samples',...
    ...'Control samples',...
    'Estimated log odds coefficient',...
    '2.5% CI of log odds coefficient',...
    '97.5% CI of log odds coefficient',...
    'Standard error',...
    'Regression t-statistic',...
    'P-value',...
    'FDR BH',...
    'Regression R-squared'};

% Apply improved names
preparedfluxRegressionTable = renamevars(fluxRegressionTable,oldNames,newNames);

end