function opt = ODEoptions

    global eventsFunctionHandle;

    opt = odeset('AbsTol',1e-009, ...
                 'BDF','on', ...
                 'InitialStep',1e-010, ...
                 'MaxOrder',5, ...
                 'MaxStep',100000, ...
                 'RelTol',0.0001, ...
                 'Events',eventsFunctionHandle ...
                );
